# train file parameters
TRAIN_IDENTITY_FILE_PATH = 'data/train_identity.csv'
TRAIN_IDENTITY_FILE_INDEX_VARIABLE = 'TransactionID'
TRAIN_TRANSACTION_FILE_PATH = 'data/train_transaction.csv'
TRAIN_TRANSACTION_FILE_INDEX_VARIABLE = 'TransactionID'

# test file parameters
TEST_IDENTITY_FILE_PATH = 'data/test_identity.csv'
TEST_IDENTITY_FILE_INDEX_VARIABLE = 'TransactionID'
TEST_TRANSACTION_FILE_PATH = 'data/test_transaction.csv'
TEST_TRANSACTION_FILE_INDEX_VARIABLE = 'TransactionID'

# target variable
TARGET_VARIABLE = 'isFraud'

# logger info
LOG_NAME = 'fraud_detection'
LOG_FILE_NAME = 'fraud_detection.log'
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# mlflow setting
MLFLOW_TRACKING_SERVER_URI = 'http://0.0.0.0:5003'
MLFLOW_EXPERIMENT_NAME = 'fraud_detection'


CATEGORICAL_VARIABLES = ['ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2',
                         'P_emaildomain', 'R_emaildomain',
                         'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'id_12', 'id_13', 'id_14', 'id_15',
                         'id_16', 'id_17',
                         'id_18', 'id_19', 'id_20', 'id_21', 'id_22', 'id_23', 'id_24', 'id_25', 'id_26', 'id_27',
                         'id_28', 'id_29',
                         'id_30', 'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType',
                         'DeviceInfo']

CATEGORICAL_VARIABLES_FILL_NAN = {
    'ProductCD': 'others',
    'P_emaildomain': 'others.others',
    'R_emaildomain': 'others.others',
    'card4': 'others',
    'card6': 'others',
    'M1': 'others',
    'M2': 'others',
    'M3': 'others',
    'M4': 'others',
    'M5': 'others',
    'M6': 'others',
    'M7': 'others',
    'M8': 'others',
    'M9': 'others',
    'id_12': 'others',
    'id_15': 'others',
    'id_16': 'others',
    'id_23': 'others',
    'id_27': 'others',
    'id_28': 'others',
    'id_29': 'others',
    'id_30': 'others',
    'id_31': 'others',
    'id_34': 'others',
    'id_35': 'others',
    'id_36': 'others',
    'id_37': 'others',
    'id_38': 'others',
    'DeviceType': 'others',
    'DeviceInfo': 'others',
    'card1': -9999,
    'card2': -9999,
    'card3': -9999,
    'card5': -9999,
    'addr1': -9999,
    'addr2': -9999,
    'id_13': -9999,
    'id_14': -9999,
    'id_17': -9999,
    'id_18': -9999,
    'id_19': -9999,
    'id_20': -9999,
    'id_21': -9999,
    'id_22': -9999,
    'id_24': -9999,
    'id_25': -9999,
    'id_26': -9999,
    'id_32': -9999,
    'id_33': -9999,
}

# MODEL_FILE_PATH = "model/model_selected_features.pickle"
MODEL_FILE_PATH = "model/model.pickle"
MLFLOW_MODEL_DOWNLOAD_PATH = 'model/'
# LIGHTGMB_MODEL_PARAMS = {
#     'boosting': 'dart',
#     'num_iterations': 10000,
#     'objective': 'binary',
#     'metric': 'auc',
#     'is_unbalance': True,
#     'boost_from_average': True,
#     'num_threads': 4,
#     'num_leaves': 500,
#     # 'min_data_in_leaf': 25,
#     'max_depth': -1,
#     'learning_rate': 0.001,
#     'max_bin': 300,
# }

# # Initiale Parameters
LIGHTGMB_MODEL_PARAMS  = {
    'objective': 'binary',
    'metric': 'auc',
    'is_unbalance': True,
    'boost_from_average': True,
    'num_threads': 4,
    'num_leaves': 500,
    # 'min_data_in_leaf': 25,
    'max_depth': -1,
    'learning_rate': 0.01
}
# LIGHTGMB_MODEL_PARAMS = {
#                     'objective':'binary',
#                     'boosting_type':'gbdt',
#                     'metric':'auc',
#                     'n_jobs':-1,
#                     'learning_rate':0.01,
#                     'num_leaves': 2**8,
#                     'max_depth':-1,
#                     'tree_learner':'serial',
#                     'colsample_bytree': 0.7,
#                     'subsample_freq':1,
#                     'subsample':1,
#                     'n_estimators':800,
#                     'max_bin':255,
#                     'verbose':-1,
#                 }

SELECTED_FEATURES = ['TransactionDT',
                     'TransactionAmt',
                     'dist1',
                     'dist2',
                     'C1',
                     'C2',
                     'C4',
                     'C5',
                     'C6',
                     'C8',
                     'C9',
                     'C10',
                     'C11',
                     'C12',
                     'C13',
                     'C14',
                     'D1',
                     'D2',
                     'D3',
                     'D4',
                     'D5',
                     'D6',
                     'D7',
                     'D8',
                     'D9',
                     'D10',
                     'D11',
                     'D13',
                     'D14',
                     'D15',
                     'V2',
                     'V3',
                     'V4',
                     'V5',
                     'V6',
                     'V7',
                     'V11',
                     'V12',
                     'V13',
                     'V19',
                     'V20',
                     'V24',
                     'V29',
                     'V35',
                     'V36',
                     'V37',
                     'V38',
                     'V45',
                     'V48',
                     'V53',
                     'V54',
                     'V55',
                     'V56',
                     'V61',
                     'V62',
                     'V66',
                     'V67',
                     'V70',
                     'V75',
                     'V76',
                     'V77',
                     'V78',
                     'V82',
                     'V83',
                     'V86',
                     'V87',
                     'V91',
                     'V96',
                     'V97',
                     'V99',
                     'V102',
                     'V124',
                     'V126',
                     'V127',
                     'V128',
                     'V129',
                     'V130',
                     'V131',
                     'V132',
                     'V133',
                     'V135',
                     'V136',
                     'V137',
                     'V139',
                     'V159',
                     'V160',
                     'V164',
                     'V165',
                     'V166',
                     'V172',
                     'V206',
                     'V209',
                     'V212',
                     'V216',
                     'V221',
                     'V228',
                     'V233',
                     'V234',
                     'V258',
                     'V263',
                     'V264',
                     'V265',
                     'V273',
                     'V280',
                     'V281',
                     'V282',
                     'V283',
                     'V285',
                     'V287',
                     'V289',
                     'V291',
                     'V292',
                     'V293',
                     'V294',
                     'V296',
                     'V297',
                     'V300',
                     'V306',
                     'V307',
                     'V308',
                     'V309',
                     'V310',
                     'V311',
                     'V312',
                     'V313',
                     'V314',
                     'V315',
                     'V316',
                     'V317',
                     'V318',
                     'V319',
                     'V320',
                     'V321',
                     'V323',
                     'V332',
                     'id_01',
                     'id_02',
                     'id_05',
                     'id_06',
                     'ProductCD',
                     'card1',
                     'card2',
                     'card3',
                     'card4',
                     'card5',
                     'card6',
                     'addr1',
                     'M1',
                     'M2',
                     'M3',
                     'M4',
                     'M5',
                     'M6',
                     'M7',
                     'M8',
                     'M9',
                     'id_13',
                     'id_14',
                     'id_15',
                     'id_17',
                     'id_18',
                     'id_19',
                     'id_20',
                     'id_30',
                     'id_31',
                     'id_33',
                     'id_34',
                     'id_38',
                     'DeviceType',
                     'DeviceInfo',
                     'P_emaildomain_vendor',
                     'P_emaildomain_extension',
                     'R_emaildomain_vendor',
                     'R_emaildomain_extension']
